### ISSUE TITLE
大佬，你好，扫码登录，手机端显示登录成功，但是服务端报错，报错如下，帮忙看看是什么问题

### ISSUE THREAD

**Issue by cnbillsomeday** [Mikubill/efb-wechat-docker#15]
2022-01-16 05:26:52,267 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:195)
    Confirm on your phone.
2022-01-16 05:27:07,717 [Level 99]: plugins.blueset.wechat.WeChatChannel (__init__.console_qr_code; __init__.py:198)
    Successfully logged in.
2022-01-16 05:27:08,718 [ERROR]: itchat (login.verify_login; login.py:96)
    msg list retrieve failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 94, in verify_login
    msg_list, contact_list = self.get_msg()
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 384, in get_msg
    'SyncKey': self.loginInfo['SyncKey'],
KeyError: 'SyncKey'
2022-01-16 05:27:08,719 [ERROR]: itchat (login.verify_login; login.py:101)
    sync check result failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 99, in verify_login
    sync_check_result = self.sync_check()
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 352, in sync_check
    'synckey': self.loginInfo['synckey'],
KeyError: 'synckey'
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/ehforwarderbot/__main__.py", line 335, in main
    init(conf)
  File "/usr/local/lib/python3.10/site-packages/ehforwarderbot/__main__.py", line 135, in init
    coordinator.add_channel(cls(instance_id=instance_id))
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/__init__.py", line 160, in __init__
    self.authenticate('console_qr_code', first_start=True)
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/__init__.py", line 672, in authenticate
    self.bot: wxpy.Bot = wxpy.Bot(cache_path=str(efb_utils.get_data_path(self.channel_id) / "wxpy.pkl"),
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/vendor/wxpy/api/bot.py", line 85, in __init__
    self.core.auto_login(
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/vendor/itchat/components/register.py", line 32, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 77, in login
    self.verify_login()
  File "/usr/local/lib/python3.10/site-packages/efb_wechat_slave/vendor/itchat/components/login.py", line 106, in verify_login
    raise Exception('server refused, loading login status failed.')
Exception: server refused, loading login status failed.

**Comment by cnbillsomeday** [comment]
我试着直接从docker hub拉取已编译好的镜像，就没有报错，但是刚刚登录上就被退出，要重新扫码，一直这样循环
